### ISSUE TITLE
`mongoose-lean-getters` not working properly with `find` properly , calls the getter method twice

### ISSUE THREAD

**Issue by vivekdoshi2** [mongoosejs/mongoose-lean-getters#1]
I am using [**`lean`**][1], *(This makes queries faster and less memory intensive, but the result documents are plain old JavaScript objects (POJOs),)*

By default this will block all getters execution and provides POJO (plain old java object) so as a solution we can use [`mongoose-lean-getters`][2] as per the **[standard doc][3]**

**Schema :** 

    const mongooseLeanGetters = require('mongoose-lean-getters');
    const rateSchema = new Schema({
        rate_photo: {
            type: String,
            get: getFullUrl
        }
    );
    
    rateSchema.plugin(mongooseLeanGetters);
    
    const Rate = mongoose.model('rates', rateSchema);
    
    module.exports = Rate;
    
    function getFullUrl(url) {
        if (url != undefined) return `${process.env.ASSETS_URL}uploads/${url}`;
        else return '';
    }

**Issue :**

    model.Rate.find(condition).lean({ getters : true })

**Output:**

    without getter :
    "rate_photo": "rate/1574154457920-myw3schoolsimage.jpg",
    
    With getter :
    "rate_photo": "http://192.168.15.93:6600/assets/uploads/rate/1574154457920-myw3schoolsimage.jpg",
    
    With lean:
    "rate_photo": "rate/1574154457920-myw3schoolsimage.jpg",
    
    With lean and findOne:
    "rate_photo": "http://192.168.15.93:6600/assets/uploads/rate/1574154457920-myw3schoolsimage.jpg",
    
    With lean and find: // <------------ ISSUE
    expected result : 
        "rate_photo": "http://192.168.15.93:6600/assets/uploads/rate/1574154457920-myw3schoolsimage.jpg",
    BUT GOT THIS :
        "rate_photo": "http://192.168.15.93:6600/assets/uploads/http://192.168.15.93:6600/assets/uploads/rate/1574154457920-myw3schoolsimage.jpg",

-----------------------------

I have also found the **reason behind the issue**, in the npm package, they are calling getter twice via middleware **1st from `pre`** and **second from `post`** and this is only for `find` method alone :

    module.exports = function mongooseLeanGetters(schema) {
      const fn = applyGettersMiddleware(schema);
      schema.pre('find', function() { //<--------------- 1st HERE
        if (typeof this.map === 'function') {
          this.map((res) => {
            fn.call(this, res);
            return res;
          });
        } else {
          this.options.transform = (res) => {
            fn.call(this, res);
            return res;
          };
        }
      });
    
      schema.post('find', fn); //<--------------- 2nd HERE
      schema.post('findOne', fn);
      schema.post('findOneAndUpdate', fn);
    };

----------------------

So If I comment out one of them ti works great, but the code is there for some reason, so Is there any better way to go ahead ?

  [1]: https://mongoosejs.com/docs/tutorials/lean.html
  [2]: https://plugins.mongoosejs.io/plugins/lean-getters
  [3]: https://mongoosejs.com/docs/tutorials/lean.html#plugins

> I have also posted the same [question on StackOverflow ](https://stackoverflow.com/questions/58973452/mongoose-lean-getters-not-working-properly-with-find-properly-calls-the-ge)to know if this is not plugin issue

**Comment by vkarpov15** [comment]
Thanks for reporting, fix is in v0.1.2 :+1:
