### ISSUE TITLE
lean(getters: true) & populate() not working 

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [mongoosejs/mongoose-lean-getters#29]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Getters that convert ObjectId to string does not work with populate(), since it returns  '[object Object]' 

**If the current behavior is a bug, please provide the steps to reproduce.**
Define a getter for ObjectIds: mongoose.Schema.ObjectId.get(v => v != null ? v.toString() : v);
try to run a query with .lean({ getters: true }) and populate() to a schema of your choice

**What is the expected behavior?**
lean({ getters: true }) gets correctly propagated to the populated documents

**What are the versions of Node.js, mongoose-lean-getters, and Mongoose are you are using? Note that "latest" is not a version.**
18, 1.1.0, 7.4

**Comment by RiccardoRomagnoli** [comment]
@vkarpov15 Do you have any idea?

**Comment by IslandRhythms** [comment]
```javascript
const mongoose = require('mongoose');

mongoose.Schema.ObjectId.get(v => v != null ? v.toString() : v);

const testSchema = new mongoose.Schema({
  name: String,
  identifier: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Pop'
  }
});

const popSchema = new mongoose.Schema({
  name: String
});

testSchema.plugin(require('mongoose-lean-getters'));
popSchema.plugin(require('mongoose-lean-getters'));

const Test = mongoose.model('Test', testSchema);
const Pop = mongoose.model('Pop', popSchema);

async function run() {
  await mongoose.connect('mongodb://localhost:27017');
  await mongoose.connection.dropDatabase();

  const doc = await Pop.create({
    name: 'Test Testserson pop doc'
  });

  await Test.create({
    name: 'Test Testserson main doc',
    identifier: doc._id
  });

  const res = await Test.findOne().lean({ getters: true }).populate('identifier');
  console.log('what is res', res);
}

run();
```

**Comment by RiccardoRomagnoli** [comment]
[mongoose-lean-getters](https://github.com/mongoosejs/mongoose-lean-getters) is clearly not ready for production. It should be mentioned when referred from the official mongoose doc :/

**Comment by vkarpov15** [comment]
Ok yeah, the issue here is that your ObjectId getter needs to handle populated paths. The reason why you're getting string '[object Object]' is because `identifier` is correctly populated, but in `mongoose.Schema.ObjectId.get(v => v != null ? v.toString() : v);` the value of `v` can be a populated doc.

Using the following works:

```javascript
mongoose.Schema.ObjectId.get(v => v instanceof mongoose.Types.ObjectId ? v.toString() : v);
```

output:

```
what is res {
  _id: '662a62b4c0c03e5f41b1a8f8',
  name: 'Test Testserson main doc',
  identifier: {
    _id: '662a62b4c0c03e5f41b1a8f6',
    name: 'Test Testserson pop doc',
    __v: 0
  },
  __v: 0
}

```
