### ISSUE TITLE
Lean getters don't seem to work from `.loadClass`

### ISSUE THREAD

**Issue by JosephScript** [mongoosejs/mongoose-lean-getters#3]
Let's say you have a class:

```js
export class UserModel {
  get name() {
    return `${this.firstname} ${this.lastname}`
  }
}
```

And you use that in a model:

```js
const UserSchema = new Schema(
  {
    firstname: String,
    lastname: String,
  }
)
  .set('toJSON', { virtuals: true })
  .loadClass(UserModel)
  .plugin(mongooseLeanGetters)

export const UserDB = model('User', UserSchema)
```

And then when using .lean:

```js
const user = await UserDB.findById(userId)
    .lean({ getters: true, defaults: true })
    .exec()
```

The getter isn't populated:

```js
console.log(user.name) // ' '
```

**Comment by vkarpov15** [comment]
This plugin applies [getters](https://mongoosejs.com/docs/tutorials/getters-setters.html) on lean documents, not virtuals. You should use the [mongoose-lean-virtuals plugin](https://www.npmjs.com/package/mongoose-lean-virtuals) for this. Remember that `get name()` becomes a [virtual when using `loadClass()`](https://mongoosejs.com/docs/advanced_schemas.html).

**Comment by JosephScript** [comment]
OK thanks. I'll take it over there.
